[versions]
minSdk = "26"
targetSdk = "36"
compileSdk = "36"
versionCode = "12"
versionName = "1.2.0-rc"
jvmTarget = "21"

agp = "8.13.0"
kotlin = "2.2.21"
licensee = "1.14.1"
ksp = "2.3.1"
spotless = "8.0.0"

googleApiClient = "2.8.1"
googleDriveApi = "v3-rev20251019-2.0.0"
coreKtx = "1.17.0"
activityCompose = "1.11.0"
mapsCompose = "6.12.1"
placesApi = "5.0.0"
core-splashscreen = "1.2.0"
kotlinx-coroutines = "1.10.2"
room = "2.8.3"
koin = "4.1.1"
coil = "3.3.0"
kotlinx-serialization = "1.9.0"
material-motion-compose = "2.0.1"
compose-rules = "0.4.27"
navigation-compose = "2.9.1"
lifecycle-compose = "2.9.5"
jetbrains-compose = "1.9.2"
ktor = "3.3.2"
zoomable = "2.8.2"
reveal-compose = "4.0.0"
lottieCompose = "6.7.0"

junit = "4.13.2"
androidxTest = "1.3.0"
espressoCore = "3.7.0"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
profileinstaller = "1.4.1"
baselineprofile = "1.4.1"
uiTestManifest = "1.9.4"
sqlite = "2.6.1"
filekit = "0.12.0"
moko-permissions = "0.20.1"

pods-google-maps = "10.0.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
jetbrains-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-compose" }
jetbrains-lifecycle-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-compose" }
jetbrains-compose-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrains-compose" }

androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestManifest" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleDriveApi" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

moko-permissions = { module = "dev.icerock.moko:permissions", version.ref = "moko-permissions" }
moko-permissions-location = { module = "dev.icerock.moko:permissions-location", version.ref = "moko-permissions" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
places = { module = "com.google.android.libraries.places:places", version.ref = "placesApi" }
material-motion-compose = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "material-motion-compose" }
ktlint-compose-rules = { module = "io.nlopez.compose.rules:ktlint", version.ref = "compose-rules" }
zoomable-compose = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
reveal-compose = { module = "com.svenjacobs.reveal:reveal-core", version.ref = "reveal-compose" }
reveal-compose-shapes = { module = "com.svenjacobs.reveal:reveal-shapes", version.ref = "reveal-compose" }

androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTest" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Build-logic dependencies
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
composeCompiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
androidx-room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }

rafael-spotless = { id = "com.rafael.spotless", version = "unspecified" }
rafael-android-library = { id = "com.rafael.android.library", version = "unspecified" }
rafael-multiplatform-library = { id = "com.rafael.multiplatform.library", version = "unspecified" }
rafael-multiplatform-library-compose = { id = "com.rafael.compose.multiplatform.library", version = "unspecified" }
rafael-android-application = { id = "com.rafael.android.application", version = "unspecified" }
rafael-android-application-compose = { id = "com.rafael.compose.android.application", version = "unspecified" }

[bundles]
koin = [
    "koin-android",
    "koin-core",
    "koin-compose",
    "koin-core-viewmodel"
]
